<?php

/**
 * This file is part of the planb project.
 *
 * (c) jmpantoja <jmpantoja@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace PlanB\DDDBundle\Symfony\Form\Type;


use PlanB\DDD\Domain\VO\Percent;
use PlanB\DDD\Domain\VO\Validator\Constraint;
use PlanB\DDDBundle\Symfony\Form\FormDataMapper;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ToggleType extends AbstractSingleType
{
    public function customOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'on_text' => 'on',
            'off_text' => 'off',
            'on_style' => 'success',
            'off_style' => 'danger',
        ]);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['on_text'] = $options['on_text'];
        $view->vars['off_text'] = $options['off_text'];
        $view->vars['on_style'] = $options['on_style'];
        $view->vars['off_style'] = $options['off_style'];

        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }


    public function buildConstraint(array $options): ?Constraint
    {
        return null;
    }


    public function customMapping($data)
    {
        return !empty($data);
    }

}
