version: '2.4'

services:
  php:
    image: docker.io/jmpantoja/britannia-php:7.4
    logging:
      options:
        max-size: "10m"
        max-file: "3"
            
    restart: always    
    environment:
      APP_ENV: pro
      APP_DEBUG: 0

    depends_on:
      - db
      - redis
    # Comment out these volumes in production
    volumes:
      - ./api:/srv/api:rw
      - ./api/var:/srv/api/var:rw

  encore:
    image: node:10-alpine
    logging:
      options:
        max-size: "10m"
        max-file: "3"
            
    restart: always    
    volumes:
      - ./api:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app

  api:
    image: quay.io/api-platform/nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
            
    restart: always    
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./api/public:/srv/api/public:ro

  redis:
    image: redis
    restart: always    
    logging:
      options:
        max-size: "10m"
        max-file: "3"
            
    volumes:
      - ./docker/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  db:
    image: mysql:8
    restart: always    
    logging:
      options:
        max-size: "10m"
        max-file: "3"
            
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./docker/mysql:/var/lib/mysql"


