version: '3.4'

services:
  php:
    image: quay.io/api-platform/php
    build:
      context: ./api
      target: api_platform_php
      cache_from:
        - quay.io/api-platform/php
        - quay.io/api-platform/nginx
        - quay.io/api-platform/varnish
    environment:
      - APP_ENV=prod
    depends_on:
      - db
      - redis
    # Comment out these volumes in production
    volumes:
      - ./api:/srv/api:rw
      - ./api/var:/srv/api/var:rw

  encore:
    image: node:10-alpine
    volumes:
      - ./api:/app
    ports:
      - "${DEV_SERVER_PORT:-8080}:8080"
    working_dir: /app

  api:
    image: quay.io/api-platform/nginx
    build:
      context: ./api
      target: api_platform_nginx
      cache_from:
        - quay.io/api-platform/php
        - quay.io/api-platform/nginx
        - quay.io/api-platform/varnish
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./api/public:/srv/api/public:ro

  cache-proxy:
    image: quay.io/api-platform/varnish
    build:
      context: ./api
      target: api_platform_varnish
      cache_from:
        - quay.io/api-platform/php
        - quay.io/api-platform/nginx
        - quay.io/api-platform/varnish
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  db:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./data/mysql:/var/lib/mysql"


  proxy:
    image: steveltn/https-portal:1
    depends_on:
      - api
      - cache-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./proxy/ssl_certs:/var/lib/https-portal
    #    - ./proxy/conf/default.conf.erb:/var/lib/nginx-conf/default.conf.erb:ro
    #    - ./proxy/conf/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb:ro

    environment:
      CLIENT_MAX_BODY_SIZE: 64M
      DOMAINS: 'www.academiabritannia.es -> http://api:80 #production'
#      DOMAINS: 'www.academiabritannia.es -> http://cache-proxy:80 #production'

