parameters:
    discount:
        family:
            upper: 0
            lower: 15
            default: 5

        job_status:
            student: 5
            unemployed: 5
            retired: 5
            disabled: 5
