parameters:
    marks:
        unit_percent_weight: 30

    enrollment_price: 55

    discount:
        family:
            upper: 0
            lower: 15
            default: 5

        job_status:
            student: 5
            unemployed: 5
            retired: 5
            disabled: 5

    dates:
        course_starts_on:
            day: 1
            month: 9
        second_term_starts_on:
            day: 1
            month: 1
        third_term_starts_on:
            day: 1
            month: 3
        course_ends_on:
            day: 1
            month: 8
