parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:

            original:
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_OLD_URL)%'
                charset: 'UTF8'

            default:
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'
                charset: 'UTF8'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'

                mapping_types:
                    #Academy
                    AcademyId: AcademyId

                    #Book
                    BookId: BookId
                    BookCategory: BookCategory

                    #ClassRoom
                    ClassRoomId: ClassRoomId

                    #Course
                    AttendanceId: AttendanceId
                    LevelId: LevelId
                    CourseId: CourseId
                    CourseStatus: CourseStatus
                    DayOfWeek: DayOfWeek
                    Examiner: Examiner
                    Age: Age
                    Periodicity: Periodicity
                    Support: Support
                    Intensive: Intensive
                    DiscountList: DiscountList

                    #Mark
                    UnitId: UnitId
                    UnitMarkId: UnitMarkId
                    TermId: TermId
                    TermName: TermName
                    SetOfSkills: SetOfSkills
                    UnitsDefinition: UnitsDefinition
                    Mark: Mark

                    #Staff
                    StaffMemberId: StaffMemberId

                    #Student
                    SchoolId: SchoolId
                    StudentId: StudentId
                    TutorId: TutorId
                    JobStatus: JobStatus
                    PartOfDay: PartOfDay
                    NumOfYears: NumOfYears
                    ContactMode: ContactMode
                    PaymentMode: PaymentMode
                    BankAccount: BankAccount

                    #Lesson
                    LessonId: LessonId

                    #Record
                    RecordId: RecordId
                    TypeOfRecord: TypeOfRecord

        types:
            #Academy
            AcademyId:  Britannia\Infraestructure\Doctrine\DBAL\Type\Academy\AcademyIdType

            #Book
            BookId: Britannia\Infraestructure\Doctrine\DBAL\Type\Book\BookIdType
            BookCategory: Britannia\Infraestructure\Doctrine\DBAL\Type\Book\BookCategoryType

            #Classroom
            ClassRoomId: Britannia\Infraestructure\Doctrine\DBAL\Type\ClassRoom\ClassRoomIdType

            #Courses
            Age: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\AgeType
            AttendanceId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\AttendanceId
            DayOfWeek: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\DayOfWeekType
            Examiner: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\ExaminerType
            Intensive: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\IntensiveType
            Periodicity: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\PeriodicityType
            Support: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\SupportType
            CourseStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\CourseStatusType
            CourseId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\CourseId
            LevelId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\LevelId
            DiscountList: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\DiscountListType


            #Mark
            UnitId: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\UnitId
            UnitMarkId: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\UnitMarkId
            TermId: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\TermId
            TermName: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\TermNameType
            SetOfSkills: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\SetOfSkillsType
            UnitsDefinition: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\UnitsDefinitionType
            Mark: Britannia\Infraestructure\Doctrine\DBAL\Type\Mark\MarkType

            #Lesson
            LessonId: Britannia\Infraestructure\Doctrine\DBAL\Type\Lesson\LessonIdType

            #Record
            RecordId: Britannia\Infraestructure\Doctrine\DBAL\Type\Record\RecordId
            TypeOfRecord: Britannia\Infraestructure\Doctrine\DBAL\Type\Record\TypeOfRecordType

            #School
            SchoolId:  Britannia\Infraestructure\Doctrine\DBAL\Type\School\SchoolIdType

            #Staff
            StaffMemberId:  Britannia\Infraestructure\Doctrine\DBAL\Type\Staff\StaffMemberIdType

            #Student
            StudentId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\StudentIdType
            TutorId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\TutorIdType
            JobStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\JobStatusType
            PartOfDay: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\PartOfDayType
            NumOfYears: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\NumOfYearsType
            ContactMode: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\ContactModeType
            PaymentMode: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\PaymentModeType
            BankAccount: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\BankAccountType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Britannia:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine'
                prefix: 'Britannia\Domain'
                alias: Britannia

