parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:

            original:
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_OLD_URL)%'
                charset: 'UTF8'
                
            default: 
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'
                charset: 'UTF8'
        
                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'
                
                mapping_types:
                    StaffMemberId: StaffMemberId
                    AcademyId: AcademyId
                    SchoolId: SchoolId
                    StudentId: StudentId
                    TutorId: TutorId
                    JobStatus: JobStatus
                    PartOfDay: PartOfDay
                    NumOfYears: NumOfYears
                    ContactMode: ContactMode
                    PaymentMode: PaymentMode
                    BankAccount: BankAccount
        
        types:
            StaffMemberId:  Britannia\Infraestructure\Doctrine\DBAL\Type\StaffMemberIdType
            AcademyId:  Britannia\Infraestructure\Doctrine\DBAL\Type\AcademyIdType
            SchoolId:  Britannia\Infraestructure\Doctrine\DBAL\Type\SchoolIdType
            StudentId: Britannia\Infraestructure\Doctrine\DBAL\Type\StudentIdType
            TutorId: Britannia\Infraestructure\Doctrine\DBAL\Type\TutorIdType
            JobStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\JobStatusType
            PartOfDay: Britannia\Infraestructure\Doctrine\DBAL\Type\PartOfDayType
            NumOfYears: Britannia\Infraestructure\Doctrine\DBAL\Type\NumOfYearsType
            ContactMode: Britannia\Infraestructure\Doctrine\DBAL\Type\ContactModeType
            PaymentMode: Britannia\Infraestructure\Doctrine\DBAL\Type\PaymentModeType
            BankAccount: Britannia\Infraestructure\Doctrine\DBAL\Type\BankAccountType


    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Britannia:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine'
                prefix: 'Britannia\Domain'
                alias: Britannia

