parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:

            original:
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_OLD_URL)%'
                charset: 'UTF8'

            default:
                logging: true
                # configure these for your database server
                driver: 'mysql'
                server_version: '5.7'
                charset: 'UTF8'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'

                mapping_types:
                    #Academy
                    AcademyId: AcademyId

                    #Book
                    BookId: BookId
                    BookCategory: BookCategory

                    #ClassRoom
                    ClassRoomId: ClassRoomId

                    #Course
                    AttendanceId: AttendanceId
                    LevelId: LevelId
                    CourseId: CourseId
                    CourseStatus: CourseStatus
                    DayOfWeek: DayOfWeek
                    Examiner: Examiner
                    Intensive: Intensive
                    JobStatusDiscountList: JobStatusDiscountList
                    FamilyDiscountList: FamilyDiscountList
                    PassId: PassId
                    PassHours: PassHours

                    #Assessment
                    TermName: TermName
                    SetOfSkills: SetOfSkills
                    SkillList: SkillList
                    Skill: Skill
                    Mark: Mark
                    MarkReport: MarkReport
                    UnitId: UnitId
                    SkillMarkId: SkillMarkId
                    TermId: TermId

                    #Staff
                    StaffMemberId: StaffMemberId

                    #School
                    SchoolId: SchoolId

                    #SchoolCourse
                    SchoolCourseId: SchoolCourseId
                    SchoolLevel: SchoolLevel


                    #Student                    
                    StudentId: StudentId
                    AttachmentId: AttachmentId
                    TutorId: TutorId
                    JobStatus: JobStatus
                    PartOfDay: PartOfDay
                    NumOfYears: NumOfYears
                    ContactMode: ContactMode
                    PaymentMode: PaymentMode
                    BankAccount: BankAccount
                    Alert: Alert

                    #Lesson
                    LessonId: LessonId

                    #Notification
                    NotificationId: NotificationId
                    TypeOfNotification: TypeOfNotification

                    #Image
                    ImageId: ImageId

                    #Setting
                    SettingId: SettingId

                    #Issue
                    IssueId: IssueId
                    IssueRecipientId: IssueRecipientId

                    #Message
                    MessageId: MessageId
                    ShipmentId: ShipmentId
                    TemplateId: TemplateId
                    MessageMailer: MessageMailer

        types:
            #Academy
            AcademyId:  Britannia\Infraestructure\Doctrine\DBAL\Type\Academy\AcademyIdType

            #Book
            BookId: Britannia\Infraestructure\Doctrine\DBAL\Type\Book\BookIdType
            BookCategory: Britannia\Infraestructure\Doctrine\DBAL\Type\Book\BookCategoryType

            #Classroom
            ClassRoomId: Britannia\Infraestructure\Doctrine\DBAL\Type\ClassRoom\ClassRoomIdType

            #Attendance
            AttendanceId: Britannia\Infraestructure\Doctrine\DBAL\Type\Attendance\AttendanceId

            #Courses
            DayOfWeek: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\DayOfWeekType
            Examiner: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\ExaminerType
            Intensive: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\IntensiveType
            CourseStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\CourseStatusType
            CourseId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\CourseId
            PassId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\PassId
            LevelId: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\LevelId
            PassHours: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\PassHoursType
            JobStatusDiscountList: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\JobStatusDiscountListType
            FamilyDiscountList: Britannia\Infraestructure\Doctrine\DBAL\Type\Course\FamilyDiscountListType

            #Assessment
            TermName: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\TermNameType
            SetOfSkills: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\SetOfSkillsType
            SkillList: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\SkillListType
            Skill: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\SkillType
            Mark: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\MarkType
            MarkReport: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\MarkReportType
            UnitId: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\UnitId
            SkillMarkId: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\SkillMarkId
            TermId: Britannia\Infraestructure\Doctrine\DBAL\Type\Assessment\TermId

            #Lesson
            LessonId: Britannia\Infraestructure\Doctrine\DBAL\Type\Lesson\LessonIdType

            #NotificationId
            NotificationId: Britannia\Infraestructure\Doctrine\DBAL\Type\Notification\NotificationId
            TypeOfNotification: \Britannia\Infraestructure\Doctrine\DBAL\Type\Notification\TypeOfNotificationType

            #School
            SchoolId:  Britannia\Infraestructure\Doctrine\DBAL\Type\School\SchoolIdType

            #SchoolCourse
            SchoolCourseId:  Britannia\Infraestructure\Doctrine\DBAL\Type\SchoolCourse\SchoolCourseIdType
            SchoolLevel:  Britannia\Infraestructure\Doctrine\DBAL\Type\SchoolCourse\SchoolLevelType

            #Staff
            StaffMemberId:  Britannia\Infraestructure\Doctrine\DBAL\Type\Staff\StaffMemberIdType

            #Student
            StudentId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\StudentIdType
            AttachmentId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\AttachmentIdType
            StudentCourseId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\StudentCourseIdType
            TutorId: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\TutorIdType
            JobStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\JobStatusType
            PartOfDay: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\PartOfDayType
            NumOfYears: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\NumOfYearsType
            ContactMode: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\ContactModeType
            PaymentMode: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\PaymentModeType
            BankAccount: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\BankAccountType
            Alert: Britannia\Infraestructure\Doctrine\DBAL\Type\Student\AlertType

            #Image
            ImageId: Britannia\Infraestructure\Doctrine\DBAL\Type\Image\ImageIdType

            #Setting
            SettingId: Britannia\Infraestructure\Doctrine\DBAL\Type\Setting\SettingIdType

            #Issue
            IssueId: Britannia\Infraestructure\Doctrine\DBAL\Type\Issue\IssueIdType
            IssueRecipientId: Britannia\Infraestructure\Doctrine\DBAL\Type\Issue\IssueRecipientIdType

            #Message
            MessageId: Britannia\Infraestructure\Doctrine\DBAL\Type\Message\MessageIdType
            ShipmentId: Britannia\Infraestructure\Doctrine\DBAL\Type\Message\ShipmentIdType
            TemplateId: Britannia\Infraestructure\Doctrine\DBAL\Type\Message\TemplateIdType
            MessageMailer: Britannia\Infraestructure\Doctrine\DBAL\Type\Message\MessageMailerType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                DAY: DoctrineExtensions\Query\Mysql\Day
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
        mappings:
            Britannia:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine'
                prefix: 'Britannia\Domain'
                alias: Britannia

