parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'mysql'
        server_version: '10'

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'

        types:
            StaffMemberId:  Britannia\Infraestructure\Doctrine\DBAL\Type\StaffMemberIdType
            AcademyId:  Britannia\Infraestructure\Doctrine\DBAL\Type\AcademyIdType
            StudentId: Britannia\Infraestructure\Doctrine\DBAL\Type\StudentIdType
            JobStatus: Britannia\Infraestructure\Doctrine\DBAL\Type\JobStatusType
            PartOfDay: Britannia\Infraestructure\Doctrine\DBAL\Type\PartOfDayType
            NumOfYears: Britannia\Infraestructure\Doctrine\DBAL\Type\NumOfYearsType
            ContactMode: Britannia\Infraestructure\Doctrine\DBAL\Type\ContactModeType
            PaymentMode: Britannia\Infraestructure\Doctrine\DBAL\Type\PaymentModeType
            BankAccount: Britannia\Infraestructure\Doctrine\DBAL\Type\BankAccountType

        mapping_types:
            StaffMemberId: StaffMemberId
            AcademyId: AcademyId
            StudentId: StudentId
            JobStatus: JobStatus
            PartOfDay: PartOfDay
            NumOfYears: NumOfYears
            ContactMode: ContactMode
            PaymentMode: PaymentMode
            BankAccount: BankAccount
            
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Britannia:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine'
                prefix: 'Britannia\Domain'
                alias: Britannia

