sonata_doctrine_orm_admin:
    templates:
        form:
        - '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'
        - '@PlanBDDD/Form/form_admin.html.twig'
        - '@PlanBDDD/Form/widgets.html.twig'
        
        - 'form/widgets.html.twig'


        filter: [ '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig' ]
