sonata_core:
    form:
        mapping:
            enabled: false


sonata_doctrine_orm_admin:
    templates:
        form:
            - '@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig'
            - 'form/form_admin.html.twig'
            - 'form/widgets.html.twig'
        
        filter: [ '@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig' ]
