sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    options:
        html5_validate: false
        use_select2:    true

    assets:
        extra_stylesheets:
        - css/admin/forms.css

        extra_javascripts:
            - js/admin/forms.js

    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
