sonata_admin:
    title: 'Britannia'
    title_logo: '/images/admin/logo_50.png'
    show_mosaic_button: false

    options:
        html5_validate: false
        use_select2:    true
        use_stickyforms: false
        title_mode: 'single_image'

    dashboard:
        groups:
            admin.group.staff:
                label: Usuarios
                label_catalogue: App
                icon: "<i class=\"fa fa-user\"></i>"
                items:
                    - admin.staff_member

            admin.group.students:
                label: Alumnos
                label_catalogue: App
                icon: "<i class=\"fa fa-graduation-cap\"></i>"
                items:
                    - admin.student
                    - admin.tutor

            admin.group.courses:
                label: Cursos
                label_catalogue: App
                icon: "<i class=\"fa fa-book\"></i>"
                items:
                    - admin.course
                    - admin.mark
                    - admin.attendance
                    - admin.report


            admin.group.tools:
                label: Herramientas
                label_catalogue: App
                icon: "<i class=\"fa fa-wrench\"></i>"
                items:
                    -   route:        planning
                        label:        Planning
                        roles: ['ROLE_MANAGER']

                    - admin.record

            admin.group.extra:
                label: Configuración
                label_catalogue: App
                icon: "<i class=\"fa fa-cog\"></i>"
                items:
                    - admin.academy
                    - admin.school
                    - admin.classroom
                    - admin.book
                    - admin.level
                    - admin.calendar
                    - admin.school_course

        blocks:
            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                roles: ['ROLE_RECEPTION', 'ROLE_MANAGER']
                settings:
                    code:  admin.student
                    icon:  fa-graduation-cap
                    text:  Alumnos
                    color: bg-green
                    filters:
                        active: { value: 1 }

            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                roles: ['ROLE_RECEPTION', 'ROLE_MANAGER']
                settings:
                    code:  admin.course
                    icon:  fa-book
                    text:  Cursos
                    color: bg-blue
                    filters:
                        status: { value: ACTIVE }

            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                roles: ['ROLE_RECEPTION', 'ROLE_MANAGER']
                settings:
                    code:  admin.staff_member
                    icon:  fa-user
                    text:  Profesores
                    color: bg-aqua
                    filters:
                        teacher: { value: 1 }

    templates:
        user_block: admin/core/user_block.html.twig
        layout: admin/core/standard_layout.html.twig
        ajax: admin/core/ajax_layout.html.twig

        outer_list_rows_list: admin/core/CRUD/list_outer_rows_list.html.twig
        inner_list_row: admin/core/CRUD/list_inner_row.html.twig
        list: admin/core/CRUD/list.html.twig
        edit: admin/core/CRUD/edit.html.twig
        base_list_field: admin/core/CRUD/base_list_field.html.twig
        button_create: admin/core/Button/create_button.html.twig
        button_list: admin/core/Button/list_button.html.twig

    assets:
        extra_stylesheets:
            - css/admin/multi.css
            - css/admin/core.css
            - css/admin/list.css
            - css/admin/forms.css
            - css/admin/attendance.css
            - css/admin/students.css
            - css/admin/widgets.css
            - css/toggle/bootstrap-toggle.min.css

            - css/fullcalendar/core.min.css
            - css/fullcalendar/daygrid.min.css
            - css/fullcalendar/timegrid.min.css

            - css/admin/fullcalendar.css

            - css/toast/jquery.toast.min.css

            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css

        extra_javascripts:
            - js/admin/multi.js
            - js/admin/forms.js
            - js/toggle/bootstrap-toggle.min.js

            - js/fullcalendar/core.min.js
            - js/fullcalendar/daygrid.min.js
            - js/fullcalendar/timegrid.min.js
            - js/fullcalendar/interaction.min.js

            - js/fullcalendar/resource-common.min.js
            - js/fullcalendar/resource-daygrid.min.js
            - js/fullcalendar/resource-timegrid.min.js

            - js/toast/jquery.toast.min.js

            - bundles/fosckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js

    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
