sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    options:
        html5_validate: false
        use_select2:    true

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
