twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        attendances: '@Britannia\Infraestructure\Symfony\Service\Attendance\AttendanceService'

    form_themes:    
    - '@SonataFormatter/Form/formatter.html.twig'
    - '@SonataCore/Form/datepicker.html.twig'
#    - '@SonataCore/Form/color.html.twig'

    
