Britannia\Domain\Entity\Staff\StaffMember:
    constraints:
    - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [userName]
          
    - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [email]
          
    properties:
        userName:
        - NotBlank: ~
        email:
        - Email: ~
