Britannia\Domain\Entity\Message\Template\EmailTemplate:
    constraints:
    - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [name]
          
    - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [purpose]          
