Britannia\Domain\Entity\Staff\StaffMember:
    constraints:
    - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [userName]
                  
    properties:
        userName:
        - NotBlank: ~
