Britannia\Domain\Entity\Student\Student:
    properties:          
#        fullName:
#        - Valid: ~

#        birthDate:
#        - NotBlank: ~            
#        - NotNull: ~            
#        - Date: ~
#
#        email:
#        - NotBlank: ~
#
#        address:
#        - Valid: ~           
