version: '3.4'
services:
  php:
    environment:
      - APP_ENV=dev
      - PHP_IDE_CONFIG=serverName=symfony-demo
      - XDEBUG_CONFIG=remote_host=192.168.1.128

  db:
    ports:
      - "3306:3306"

  proxy:
    environment:
      CLIENT_MAX_BODY_SIZE: 64M
      DOMAINS: 'www.academiabritannia.local -> http://api:80 #local'
      #DOMAINS: 'www.academiabritannia.local -> http://cache-proxy:80 #local'


