services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    admin.staff_member:
        class: Britannia\Infraestructure\Symfony\Admin\Staff\StaffAdmin
        arguments: [~, Britannia\Domain\Entity\Staff\StaffMember, ~]
        calls:
            - [setTemplate, ['profile', 'admin/staff/profile.html.twig']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Plantilla }
        public: true

    admin.student:
        class: Britannia\Infraestructure\Symfony\Admin\Student\StudentAdmin
        arguments: [~, Britannia\Domain\Entity\Student\Student, Britannia\Infraestructure\Symfony\Controller\Admin\StudentController]
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, label: Alumnos }
        calls:
            - [setSubClasses, [{child: Britannia\Domain\Entity\Student\Child, adult: Britannia\Domain\Entity\Student\Adult}]]

    admin.notification:
        class: Britannia\Infraestructure\Symfony\Admin\Notification\NotificationAdmin
        arguments: [~, Britannia\Domain\Entity\Notification\Notification, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Historial }
        public: true
#
#    admin.tutor:
#        class: Britannia\Infraestructure\Symfony\Admin\Tutor\TutorAdmin
#        arguments: [~, Britannia\Domain\Entity\Student\Tutor, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Tutores }
#
#        public: true

    admin.course:
        class: Britannia\Infraestructure\Symfony\Admin\Course\CourseAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Course, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cursos }
        calls:
            - [setSubClasses, [{
                                intensive: Britannia\Domain\Entity\Course\Course\Intensive,    
                                adult: Britannia\Domain\Entity\Course\Course\Adult,
                                school: Britannia\Domain\Entity\Course\Course\School,
                                pre_school: Britannia\Domain\Entity\Course\Course\PreSchool,
                                support: Britannia\Domain\Entity\Course\Course\Support,
                                one_to_one: Britannia\Domain\Entity\Course\Course\OneToOne,
                               }]]
        public: true

    admin.mark:
        class: Britannia\Infraestructure\Symfony\Admin\Mark\MarkAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Course, Britannia\Infraestructure\Symfony\Controller\Admin\MarkController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Calificaciones,  }
        calls:
            - [setTemplate, ['edit', 'form/mark/edit.html.twig']]
        public: true

    admin.report:
        class: Britannia\Infraestructure\Symfony\Admin\CourseReport\CourseReportAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Course, Britannia\Infraestructure\Symfony\Controller\Admin\CourseReportController]
        calls:
            - [setTemplate, ['edit', 'form/report/edit.html.twig']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Informes }
        public: true

    admin.academy:
        class: Britannia\Infraestructure\Symfony\Admin\Academy\AcademyAdmin
        arguments: [~, Britannia\Domain\Entity\Academy\Academy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Otras academias }
        public: true

    admin.school:
        class: Britannia\Infraestructure\Symfony\Admin\School\SchoolAdmin
        arguments: [~, Britannia\Domain\Entity\School\School, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Escuelas }
        public: true

    admin.classroom:
        class: Britannia\Infraestructure\Symfony\Admin\ClassRoom\ClassRoomAdmin
        arguments: [~, Britannia\Domain\Entity\ClassRoom\ClassRoom, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Aulas }
        public: true

    admin.calendar:
        class: Britannia\Infraestructure\Symfony\Admin\Calendar\CalendarAdmin
        arguments: [~, Britannia\Domain\Entity\Calendar\Calendar, Britannia\Infraestructure\Symfony\Controller\Admin\CalendarController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Calendario }
        public: true

    admin.student_course:
        class: Britannia\Infraestructure\Symfony\Admin\StudentCourse\StudentCourseAdmin
        arguments: [~, Britannia\Domain\Entity\Student\StudentCourse, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: StudentCourse }
        public: true

    admin.book:
        class: Britannia\Infraestructure\Symfony\Admin\Book\BookAdmin
        arguments: [~, Britannia\Domain\Entity\Book\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Libros }
        public: true

    admin.setting:
        class: Britannia\Infraestructure\Symfony\Admin\Setting\SettingAdmin
        arguments: [~, Britannia\Domain\Entity\Setting\Setting, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Setting }
        public: true


    admin.issue:
        class: Britannia\Infraestructure\Symfony\Admin\Issue\IssueAdmin
        arguments: [~, Britannia\Domain\Entity\Issue\Issue, Britannia\Infraestructure\Symfony\Controller\Admin\IssueController]
        calls:
            - [setTemplate, ['edit', 'admin/issue/issue_edit_template.html.twig']]
            - [setTemplate, ['show', 'admin/issue/issue_show_template.html.twig']]
            - [setTemplate, ['list', 'admin/issue/issue_list_template.html.twig']]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Observaciones }
        
        public: true

    admin.message:
        class: Britannia\Infraestructure\Symfony\Admin\Message\MessageAdmin
        arguments: [~, Britannia\Domain\Entity\Message\Message, Britannia\Infraestructure\Symfony\Controller\Admin\MessageController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mensajes }
        calls:
            - [setSubClasses, [{email: Britannia\Domain\Entity\Message\Message\Email, sms: Britannia\Domain\Entity\Message\Message\Sms }]]
            - [setTemplate, ['edit', 'admin/message/message_edit_template.html.twig']]
        public: true

    admin.message.template:
        class: Britannia\Infraestructure\Symfony\Admin\MessageTemplate\TemplateAdmin
        arguments: [~, Britannia\Domain\Entity\Message\Template, ~]

        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Plantillas }

        calls:
            - [setSubClasses, [{email: Britannia\Domain\Entity\Message\Template\EmailTemplate, sms: Britannia\Domain\Entity\Message\Template\SmsTemplate }]]
            - [setTemplate, ['edit', 'admin/template/template_edit_template.html.twig']]
        public: true


    admin.invoice:
        class: Britannia\Infraestructure\Symfony\Admin\Invoice\InvoiceAdmin
        arguments: [~, Britannia\Domain\Entity\Invoice\Invoice, Britannia\Infraestructure\Symfony\Controller\Admin\InvoiceController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Recibos }
        public: true


    admin.teacher_course:
        class: Britannia\Infraestructure\Symfony\Admin\TeacherCourse\TeacherCourseAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Course, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Mis Cursos }
        #
        #        calls:
        #            - [setTemplate, ['edit', 'admin/teacher/teacher_edit_template.html.twig']]            
        public: true
