# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: admins.yaml }

parameters:
    locale: es


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Sonata\AdminBundle\Command\GenerateObjectAclCommand:
        class: Sonata\AdminBundle\Command\GenerateObjectAclCommand
        public: true
        arguments:
            - '@sonata.admin.pool'
            - []
            - ~
        tags: ['console.command']


    Sonata\Form\Date\MomentFormatConverter:
        alias: sonata.core.date.moment_format_converter


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Britannia\:
        resource: '../src/Britannia/*'

    # makes classes in src/Infraestructure available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Britannia\Infraestructure\:
        resource: '../src/Britannia/Infraestructure/*'
        exclude: '../src/Britannia/Infraestructure/Symfony/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    Britannia\Domain\Entity\Setting\Setting:
        class: Britannia\Domain\Entity\Setting\Setting
        factory: '@Britannia\Infraestructure\Symfony\Service\Setting\SettingFactory'


    Britannia\Domain\Service\Message\MailerFactoryInterface:
        class: Britannia\Infraestructure\Symfony\Service\Message\MailerFactory
        public: true
        calls:
            - [addMailer, ['MANAGERS', '@swiftmailer.mailer.managers', 'britannia.elpuerto.gestion@gmail.com', 'Gestión Academia Britannia']]
            - [addMailer, ['RECEPTION', '@swiftmailer.mailer.reception', 'britannia.elpuerto.recepcion@gmail.com', 'Recepción Academia Britannia']]
            - [addMailer, ['TEACHERS', '@swiftmailer.mailer.teachers', 'britannia.elpuerto.teachers@gmail.com', 'Teachers  Academia Britannia']]


    #    Britannia\Domain\Service\Message\SmsLauncherInterface:
    #        class: Britannia\Infraestructure\Symfony\Service\Message\DescomSMSLauncher
    #        public: true
    #        arguments:
    #            - '@eight_points_guzzle.client.descom'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Britannia\Infraestructure\Symfony\Controller\:
        resource: '../src/Britannia/Infraestructure/Symfony/Controller/*'
        tags: ['controller.service_arguments']

    Britannia\Infraestructure\Symfony\Importer\Etl\:
        resource: '../src/Britannia/Infraestructure/Symfony/Importer/Etl/*'
        arguments:
            - '@doctrine.dbal.original_connection'
    #            - '@doctrine.dbal.default_connectiCon'

    Britannia\Infraestructure\Symfony\Importer\ImporterManager:
        calls:
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StaffEtl']]
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StudentEtl']]
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\AttachmentEtl']]
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\RelativesEtl']]
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\CourseEtl']]
            #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\TeacherCoursesEtl']]
            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\InvoiceEtl']]
              #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StudentCoursesEtl']]
              #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\IssueEtl']]
              #            - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\MessageEtl']]

            #- [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\AttendanceControlEtl']]


    event_dispatcher:
        class: PlanB\DDD\Domain\Event\EventDispatcher
        factory: ['PlanB\DDD\Domain\Event\EventDispatcher', 'getInstance']
        public: true

