# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Britannia\:
        resource: '../src/Britannia/*'

    # makes classes in src/Infraestructure available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Britannia\Infraestructure\:
        resource: '../src/Britannia/Infraestructure/*'
        exclude: '../src/Britannia/Infraestructure/Symfony/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Britannia\Infraestructure\Symfony\Controller\:
        resource: '../src/Britannia/Infraestructure/Symfony/Controller/*'
        tags: ['controller.service_arguments']



    Britannia\Infraestructure\Symfony\Importer\Etl\:
        resource: '../src/Britannia/Infraestructure/Symfony/Importer/Etl/*'
        arguments:
        - '@doctrine.dbal.original_connection'
    #            - '@doctrine.dbal.default_connection'


    Britannia\Infraestructure\Symfony\Importer\ImporterManager:
        calls:
        # - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StudentEtl']]
        # - [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\CourseEtl']]
        #- [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StudentCoursesEtl']]
        #- [addEtl, ['@Britannia\Infraestructure\Symfony\Importer\Etl\StaffEtl']]


    admin.staff_member:
        class: Britannia\Infraestructure\Symfony\Admin\StaffMemberAdmin
        arguments: [~, Britannia\Domain\Entity\Staff\StaffMember, ~]
        calls:
        - [setTemplate, ['profile', 'admin/staff/profile.html.twig']]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Personal }
        public: true

    admin.student:
        class: Britannia\Infraestructure\Symfony\Admin\StudentAdmin
        arguments: [~, Britannia\Domain\Entity\Student\Student, ~]
        public: true
        tags:
        - { name: sonata.admin, manager_type: orm, group: Alumnos, label: Alumnos, pager_type: 'simple' }
        calls:
        - [setSubClasses, [{child: Britannia\Domain\Entity\Student\Child, adult: Britannia\Domain\Entity\Student\Adult}]]

    admin.tutor:
        class: Britannia\Infraestructure\Symfony\Admin\TutorAdmin
        arguments: [~, Britannia\Domain\Entity\Student\Tutor, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Alumnos, label: Tutores, pager_type: 'simple' }

        public: true

    admin.course:
        class: Britannia\Infraestructure\Symfony\Admin\CourseAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Course, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Cursos, label: Cursos, pager_type: 'simple' }
        public: true

    admin.book:
        class: Britannia\Infraestructure\Symfony\Admin\BookAdmin
        arguments: [~, Britannia\Domain\Entity\Book\Book, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Cursos, label: Libros, pager_type: 'simple' }
        public: true

    admin.level:
        class: Britannia\Infraestructure\Symfony\Admin\LevelAdmin
        arguments: [~, Britannia\Domain\Entity\Course\Level, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Cursos, label: Niveles, pager_type: 'simple'}
        public: true

    admin.academy:
        class: Britannia\Infraestructure\Symfony\Admin\AcademyAdmin
        arguments: [~, Britannia\Domain\Entity\Academy\Academy, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Datos Extra, label: Otras academias, pager_type: 'simple' }
        public: true

    admin.school:
        class: Britannia\Infraestructure\Symfony\Admin\SchoolAdmin
        arguments: [~, Britannia\Domain\Entity\School\School, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Datos Extra, label: Escuelas, pager_type: 'simple' }
        public: true

    admin.classroom:
        class: Britannia\Infraestructure\Symfony\Admin\ClassRoomAdmin
        arguments: [~, Britannia\Domain\Entity\ClassRoom\ClassRoom, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Datos Extra, label: Aulas, pager_type: 'simple' }
        public: true


    admin.calendar:
        class: Britannia\Infraestructure\Symfony\Admin\CalendarAdmin
        arguments: [~, Britannia\Domain\Entity\Calendar\Calendar, Britannia\Infraestructure\Symfony\Controller\Admin\CalendarController]
        tags:
        - { name: sonata.admin, manager_type: orm, group: Datos Extra, label: Calendario }
        public: true
