<?php

declare(strict_types=1);

namespace Britannia\Infraestructure\Symfony\Admin;

use Britannia\Domain\Entity\Student\Adult;
use Britannia\Domain\VO\SchoolCourse;
use Britannia\Infraestructure\Symfony\Form\ContactModeType;
use Britannia\Infraestructure\Symfony\Form\JobType;
use Britannia\Infraestructure\Symfony\Form\OtherAcademyType;
use Britannia\Infraestructure\Symfony\Form\PartOfDayType;
use Britannia\Infraestructure\Symfony\Form\PaymentType;
use Britannia\Infraestructure\Symfony\Form\RelativesType;
use Britannia\Infraestructure\Symfony\Form\SchoolCourseType;
use Britannia\Infraestructure\Symfony\Form\SchoolCourseTypeextends;
use Britannia\Infraestructure\Symfony\Form\TutorType;
use Doctrine\ORM\QueryBuilder;
use PlanB\DDDBundle\Symfony\Form\Type\DateType;
use PlanB\DDDBundle\Symfony\Form\Type\DNIType;
use PlanB\DDDBundle\Symfony\Form\Type\EmailListType;
use PlanB\DDDBundle\Symfony\Form\Type\FullNameType;
use PlanB\DDDBundle\Symfony\Form\Type\PhoneNumberListType;
use PlanB\DDDBundle\Symfony\Form\Type\PostalAddressType;
use PlanB\DDDBundle\Symfony\Form\Type\WYSIWYGType;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery;
use Sonata\Form\Type\DatePickerType;
use Sonata\FormatterBundle\Form\Type\SimpleFormatterType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class StudentAdmin extends AbstractAdmin
{

    public function getBatchActions()
    {
        $actions = parent::getBatchActions();
        unset($actions['delete']);

        return $actions;
    }

    public function getExportFields()
    {
        $fields = parent::getExportFields(); // TODO: Change the autogenerated stub

        unset($fields['payment.account']);
        return $fields;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper): void
    {
        $datagridMapper
            ->add('active')
            ->add('fullName', 'doctrine_orm_callback', [
                'callback' => function(ProxyQuery $queryBuilder, $alias, $field, $value) {

                    if (!$value['value']) {
                        return;
                    }

                    $queryBuilder
                        ->andwhere('o.fullName.firstName like :name OR o.fullName.lastName like :name')
                        ->setParameter('name', sprintf('%%%s%%', $value['value']))
                    ;
                    return true;
                }
            ])
        ;
    }

    protected function configureListFields(ListMapper $listMapper): void
    {
        $listMapper
            ->addIdentifier('id', 'string', [
                'template' => 'admin/student/student_list_field.html.twig',
                'label' => 'Alumnos'
            ])
//            atajos (observaciones, historial, pagos, etc)
//            ->add('_action', null, [
//                'actions' => [
//                    'show' => [],
//                    'edit' => [],
//                    'delete' => [],
//                ],
//            ])
        ;
    }

    protected function configureFormFields(FormMapper $formMapper): void
    {


        $subject = $this->getSubject();
        $isAdult = $subject instanceof Adult;

        $formMapper
            ->with('Personal', ['tab' => true])
                ->with('Cursos', ['class'=>'col-md-12'])
                    ->add('courses')
                ->end()

                ->with('Datos personales', ['class' => 'col-md-4'])
                    ->add('fullName', FullNameType::class, [
                        'sonata_help'=> 'Escriba el nombre y apellidos del alumno',
                        'label' => 'Nombre y apellidos',
                        'required' => true
                    ])
                    ->add('birthDate', DatePickerType::class, [
                        'label' => 'Fecha de nacimiento',
                        'format' => \IntlDateFormatter::LONG,
                        'empty_data' => "\r",
                        'required' => false
                    ])
                    ->ifTrue($isAdult)
                        ->add('dni', DNIType::class, [
                            'empty_data' => null,
                            'required' => false
                        ])
                    ->ifEnd()
                ->end()
                ->with('Contacto', ['class' => 'col-md-4'])
                    ->add('address', PostalAddressType::class, [
                        'sonata_help'=>'Escriba una dirección postal',
                        'label' => 'Dirección Postal',
                        'required' => false,
                    ])
                    ->add('emails', EmailListType::class, [
                        'required' => false,
                        'label' => 'Correos Electrónicos',
                    ])
                    ->add('phoneNumbers', PhoneNumberListType::class, [
                        'required' => false,
                        'label' => 'Números de teléfono',
                    ])
                ->end()
                ->with($isAdult ? 'Profesión' : 'Colegio', ['class' => 'col-md-4'])
                    ->ifTrue($isAdult)
                        ->add('job', JobType::class, [
                            'sonata_help'=>'Escriba una ocupación y una situación laboral',
                            'required' => false,
                            'label'=>'Ocupación'
                        ])
                    ->ifEnd()

                    ->ifFalse($isAdult)
                        ->add('school', ModelType::class, [
                            'label' => 'Colegio',
                            'btn_add'=>'Nuevo colegio',
                            'placeholder' => ''
                        ])
                        ->add('schoolCourse', TextType::class, [
                            'label' => 'Próximo curso escolar',
                        ])
                    ->ifEnd()
                ->end()
            ->end()

            ->with('Pago', ['tab' => true])
                ->with('Forma de pago', ['class'=>'col-md-6'])
                    ->add('payment', PaymentType::class, [
                        'label' => false,
                        'required' => true
                    ])
                ->end()
                ->with('Descuento', ['class' => 'col-md-6'])
                    ->add('relatives', RelativesType::class, [
                        'btn_add' => false,
                        'label' => 'Familiares',
                        'studentId' => $subject->getId(),
                        'required' => false
                    ])
                ->end()
            ->end()
            ->ifFalse($isAdult)
                ->with('Tutores', ['tab' => true ])
                    ->with('Tutores')
                        ->add('firstTutorDescription', TextType::class, [
                            'label' => 'Tipo',
                            'sonata_help'=>'padre/madre/abuelo/hermano/...',
                            'required' => false
                        ])
                        ->add('firstTutor', TutorType::class, [
                            'label' => 'Tutor A',
                            'sonata_help'=>'seleccione un tutor',
                            'required' => true
                        ])
                        ->add('secondTutorDescription', TextType::class, [
                            'label' => 'Tipo',
                            'sonata_help'=>'padre/madre/abuelo/hermano/...',
                            'required' => false
                        ])
                        ->add('secondTutor', TutorType::class, [
                            'label' => 'Tutor B',
                            'sonata_help'=>'seleccione un tutor',
                            'required' => false
                        ])
                    ->end()
                ->end()
            ->ifEnd()

            ->with('Observaciones', ['tab' => true])
                ->with('Observaciones A', ['class'=>'col-md-6'])
                    ->add('firstComment', WYSIWYGType::class, [
                        'label' => false
                    ])
                ->end()
                ->with('Observaciones B', ['class'=>'col-md-6'])
                    ->add('secondComment', WYSIWYGType::class, [
                        'label' => false
                    ])
                ->end()
            ->end()


            ->with('Información Extra', ['tab' => true])
                ->with('Preferencias', ['class'=>'col-md-4'])
                    ->add('preferredPartOfDay', PartOfDayType::class, [
                        'label' => 'Horario'
                    ])
                    ->add('preferredContactMode', ContactModeType::class, [
                        'label' => 'Contacto'
                    ])
                ->end()
                ->with('Estadísticas', ['class'=>'col-md-4'])
                        ->add('otherAcademy', OtherAcademyType::class, [
                            'required' => false,
                            'label' => 'Ha estudiado antes en...',
                            'sonata_admin' => $this
                        ])
                        ->add('firstContact', TextType::class, [
                            'required' => false,
                            'label' => '¿Como nos conociste?.'
                        ])
                ->end()
                ->with('Condiciones', ['class'=>'col-md-4'])
                        ->add('termsOfUseAcademy', null, [
                            'label'=>'Acepta las condiciones de uso de la academia'
                        ])
                        ->add('termsOfUseStudent', null, [
                            'label'=>'Acepta las condiciones de uso de la academia'
                        ])
                        ->add('termsOfUseImageRigths', null, [
                            'label'=>'Consentimiento de Imagen'
                        ])
                ->end()


            ->end()
        ;
    }

    protected function configureShowFields(ShowMapper $showMapper): void
    {
        $showMapper
            ->add('active')
            ->add('id')
            ->add('fullName.firstName')
            ->add('fullName.lastName');
    }
}
