my_planning:
    path:     /admin/britannia/my/planning
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\PlanningController::custom


planning:
    path:     /admin/britannia/planning
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\PlanningController::index


planning_events:
    path:     /admin/britannia/planning/events
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\PlanningController::events

my_planning_events:
    path:     /admin/britannia/planning/my/events
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\PlanningController::customEvents



attachment_upload:
    path:     /admin/britannia/attachment/upload
    controller: \Britannia\Infraestructure\Symfony\Controller\Admin\AttachmentController::upload

attachment_download:
    path:     /admin/britannia/attachment/download/{path_to_file}
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\AttachmentController::download
    requirements:
        path_to_file: ".+"
    defaults:
        path_to_file: ""


photo_upload:
    path:     /admin/britannia/photo/upload
    controller: \Britannia\Infraestructure\Symfony\Controller\Admin\PhotoController::upload

photo_download:
    path:     /admin/britannia/photo/download/{path_to_file}
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\PhotoController::download
    requirements:
        path_to_file: ".+"
    defaults:
        path_to_file: ""


student_registration_form_report:
    path:     /admin/britannia/student-reports/{id}/registration
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\StudentReportController::registration
