admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

occupation:
    path:     /admin/britannia/occupation
    controller: Britannia\Infraestructure\Symfony\Controller\Admin\OccupationController::index
